# Generated by Django 5.2.4 on 2025-07-22 16:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="UserProfileModel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("FullName", models.CharField(blank=True, max_length=20, null=True)),
                ("Gender", models.CharField(blank=True, max_length=20, null=True)),
                ("Age", models.CharField(blank=True, max_length=20, null=True)),
                ("Email", models.CharField(blank=True, max_length=20, null=True)),
                ("Phone", models.CharField(blank=True, max_length=20, null=True)),
                ("Address", models.CharField(blank=True, max_length=20, null=True)),
                (
                    "ProfileImage",
                    models.ImageField(
                        blank=True, null=True, upload_to="Jobseeker Profiles "
                    ),
                ),
            ],
        ),
    ]
