# Generated by Django 5.2.4 on 2025-09-09 06:54

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("employeeApp", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="JobApplicationModel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(blank=True, max_length=200, null=True)),
                ("email", models.EmailField(blank=True, max_length=200, null=True)),
                (
                    "resume",
                    models.FileField(
                        blank=True, null=True, upload_to="applicant_resumes/"
                    ),
                ),
                ("applied_at", models.DateTimeField(auto_now_add=True)),
                (
                    "applicant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="applicants",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "job",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="job_applications",
                        to="employeeApp.jobpostmodel",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="UserProfileModel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("FirstName", models.CharField(blank=True, max_length=20, null=True)),
                ("LastName", models.CharField(blank=True, max_length=20, null=True)),
                ("Gender", models.CharField(blank=True, max_length=20, null=True)),
                ("Age", models.CharField(blank=True, max_length=20, null=True)),
                ("Email", models.EmailField(blank=True, max_length=20, null=True)),
                ("Phone", models.CharField(blank=True, max_length=20, null=True)),
                ("Address", models.CharField(blank=True, max_length=20, null=True)),
                (
                    "ProfileImage",
                    models.ImageField(
                        blank=True, null=True, upload_to="Jobseeker Profiles"
                    ),
                ),
                ("Aboutme", models.TextField(blank=True, null=True)),
                (
                    "Degree",
                    models.CharField(blank=True, default="", max_length=20, null=True),
                ),
                (
                    "Stream",
                    models.CharField(blank=True, default="", max_length=20, null=True),
                ),
                (
                    "Institution",
                    models.CharField(blank=True, default="", max_length=20, null=True),
                ),
                (
                    "CollegeName",
                    models.CharField(blank=True, default="", max_length=20, null=True),
                ),
                ("Start_year", models.CharField(blank=True, default="", null=True)),
                ("End_year", models.CharField(blank=True, default="", null=True)),
                (
                    "CGPA",
                    models.CharField(blank=True, default="", max_length=20, null=True),
                ),
                (
                    "Resume",
                    models.FileField(blank=True, null=True, upload_to="resumes/"),
                ),
                ("LinkdIn_url", models.URLField(blank=True, null=True)),
                ("Portfolio_link", models.URLField(blank=True, null=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="userprofilemodel",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
