# Generated by Django 5.2.4 on 2025-07-23 03:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("jobseekerApp", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="userprofilemodel",
            name="ProfileImage",
            field=models.ImageField(
                blank=True, null=True, upload_to="Jobseeker Profiles"
            ),
        ),
    ]
