# Generated by Django 5.2.4 on 2025-07-21 15:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="JobPostModel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("JobTitle", models.CharField(blank=True, max_length=100, null=True)),
                ("Company", models.CharField(blank=True, max_length=100, null=True)),
                ("Description", models.TextField()),
                ("Vacancy", models.CharField(blank=True, max_length=100, null=True)),
                ("Salary", models.CharField(blank=True, max_length=20, null=True)),
                ("Experience", models.CharField(blank=True, max_length=20, null=True)),
            ],
        ),
    ]
