# Generated by Django 5.2.4 on 2025-07-22 10:15

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("employeeApp", "0002_jobpostmodel_user"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name="jobpostmodel",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="job_posts",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
