# Generated by Django 5.2.4 on 2025-07-22 09:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accountApp", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="user",
            name="confirmpassword",
        ),
        migrations.AlterField(
            model_name="user",
            name="phone",
            field=models.CharField(max_length=10, null=True),
        ),
    ]
