# Generated by Django 5.2.4 on 2025-09-09 09:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("accountApp", "0002_commentsmodel"),
    ]

    operations = [
        migrations.RenameField(
            model_name="commentsmodel",
            old_name="event",
            new_name="event_id",
        ),
        migrations.RenameField(
            model_name="commentsmodel",
            old_name="user",
            new_name="user_id",
        ),
    ]
